/**
 * A realistic 150+ message college project-team chat used by the
 * "Load demo chat" button.
 *
 * IMPORTANT: this is *input data* only. Every summary, decision and action
 * item shown in the UI is computed from these messages at runtime by real
 * parsing + extraction + (when available) on-device model calls.
 *
 * Timestamps are relative to `now` so deadline/urgency scoring stays
 * meaningful whenever the demo is opened.
 */

import type { Message } from "../types";
import { DAY, MINUTE } from "./time";

type Raw = [minutesAgo: number, sender: string, text: string];

export function buildDemoChat(now: number = Date.now()): Message[] {
  const d = (offsetDays: number): string => {
    const x = new Date(now + offsetDays * DAY);
    return `${x.getDate()}/${x.getMonth() + 1}`;
  };
  const raw: Raw[] = [
    [4300, "System", "Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them."],
    [4295, "Rohan", "guys did everyone get added?"],
    [4294, "Priya", "yes! finally 😄"],
    [4290, "Sneha", "hi all 👋"],
    [4288, "Kabir", "present sir"],
    [4285, "Ananya", "hii"],
    [4280, "Rohan", "so we need to pick a project for the review on Monday"],
    [4278, "Priya", "I was thinking attendance system with face recognition"],
    [4275, "Sneha", "we did that last sem na"],
    [4270, "Kabir", "what about an AI note summarizer for lectures"],
    [4268, "Ananya", "that's actually useful"],
    [4265, "Rohan", "let's do something with less hardware"],
    [4260, "Priya", "AI attendance using face recognition + anti-spoofing is still good"],
    [4258, "Kabir", "anti spoofing is hard in 3 weeks"],
    [4255, "Sneha", "we can use a pretrained model"],
    [4250, "Rohan", "ok let's list options properly"],
    [4245, "Ananya", "1. attendance 2. lecture summarizer 3. hostel mess voting app"],
    [4240, "Kabir", "mess voting is too simple"],
    [4235, "Priya", "let's go with attendance"],
    [4230, "Rohan", "Aarav what do you think? you're quiet"],
    [4228, "Aarav", "I'm here, reading"],
    [4225, "Rohan", "@Aarav we need your vote, attendance or summarizer?"],
    [4220, "Aarav", "attendance is safer for demo"],
    [4218, "Priya", "decided then, attendance it is 🎉"],
    [4215, "Rohan", "DECISION: Project topic is AI Attendance System with face recognition"],
    [4210, "Kabir", "who handles the ML part"],
    [4205, "Sneha", "I can help with the dataset"],
    [4200, "Ananya", "I'll do the UI"],
    [4195, "Rohan", "fine I'll do backend"],
    [4190, "Priya", "Aarav can do the ML model, he's good at python"],
    [4188, "Aarav", "sure I can do that"],
    [4185, "Rohan", "cool"],
    [4100, "Kabir", "what dataset are we using"],
    [4095, "Sneha", "there's a public one with 5000 images"],
    [4090, "Ananya", "is it free for college projects"],
    [4085, "Sneha", "yes it's CC licensed"],
    [4080, "Aarav", "I'll check and download it"],
    [4000, "Priya", "anyone free for a quick call at 9?"],
    [3995, "Kabir", "yes"],
    [3990, "Ananya", "yes"],
    [3985, "Sneha", "can't, class till 9:30"],
    [3980, "Priya", "ok we'll record and share"],
    [3900, "Rohan", "guys review is Monday 10am, we need to submit the topic by then"],
    [3895, "Priya", "noted"],
    [3800, "Kabir", "btw what's the attendance cutoff for the review"],
    [3795, "Rohan", "75% obviously"],
    [3788, "Kabir", "I'm at 73 😭"],
    [3780, "Ananya", "lol"],
    [3770, "Sneha", "ask the prof for condonation"],
    [3700, "Priya", "sharing the spreadsheet for task tracking"],
    [3695, "Priya", "<Media omitted>"],
    [3600, "Rohan", "updated the sheet"],
    [3595, "Priya", "thx"],
    [3500, "Aarav", "dataset link https://example.org/faces-dataset"],
    [3495, "Sneha", "nice, 5.2 GB though"],
    [3490, "Kabir", "my laptop will die"],
    [3485, "Rohan", "use colab free tier"],
    [3480, "Aarav", "yeah I'll train on colab"],
    [3400, "Ananya", "what color theme for the app"],
    [3395, "Priya", "blue and white"],
    [3390, "Kabir", "dark mode or nothing"],
    [3385, "Ananya", "we can do both"],
    [3380, "Rohan", "let's keep it simple, blue"],
    [3375, "Ananya", "ok blue it is"],
    [3300, "Priya", "we should meet in person to plan"],
    [3298, "Rohan", "when?"],
    [3295, "Priya", "how about Monday 3pm in the library"],
    [3290, "Sneha", "works for me"],
    [3285, "Kabir", "same"],
    [3280, "Ananya", "works"],
    [3278, "Rohan", "Aarav you coming?"],
    [3275, "Aarav", "yes"],
    [3270, "Rohan", "DECISION: In-person planning meeting Monday 3pm at central library"],
    [3265, "Priya", "adding to calendar"],
    [3200, "Kabir", "prof said attendance app needs a database"],
    [3195, "Rohan", "we'll use postgres"],
    [3190, "Ananya", "or firebase?"],
    [3185, "Rohan", "no, college wifi blocks firebase"],
    [3180, "Priya", "postgres it is"],
    [3175, "Rohan", "DECISION: Backend DB is PostgreSQL running locally"],
    [3100, "Aarav", "model training started, will take a few hours"],
    [3095, "Sneha", "any luck"],
    [3090, "Aarav", "accuracy around 91% for now"],
    [3085, "Priya", "that's good for a demo"],
    [3080, "Kabir", "can we push it to 95"],
    [3075, "Aarav", "I'll try data augmentation"],
    [3000, "Ananya", "I need the final screens list before I design"],
    [2995, "Priya", "login, register, mark attendance, dashboard, reports"],
    [2990, "Ananya", "ok on it"],
    [2985, "Rohan", "add admin panel also"],
    [2980, "Ananya", "noted"],
    [2900, "Priya", "guys I have flu, might miss tomorrow's meeting 😷"],
    [2895, "Sneha", "take care!"],
    [2890, "Kabir", "get well soon"],
    [2885, "Rohan", "no problem, we'll update you"],
    [2800, "Rohan", "can we move the meeting to Wednesday 3pm? prof wants us in class Monday 3"],
    [2795, "Sneha", "fine by me"],
    [2790, "Ananya", "ok"],
    [2785, "Kabir", "sure"],
    [2780, "Rohan", "DECISION UPDATE: Meeting moved from Monday 3pm to Wednesday 3pm, same library"],
    [2775, "Priya", "noted, thanks"],
    [2700, "Aarav", "augmentation done, accuracy now 94.2%"],
    [2695, "Priya", "🔥"],
    [2690, "Kabir", "nice work"],
    [2600, "Ananya", "first UI drafts ready"],
    [2595, "Ananya", "<Media omitted>"],
    [2590, "Priya", "looks clean"],
    [2585, "Rohan", "good"],
    [2500, "Kabir", "we should write the synopsis too"],
    [2495, "Rohan", "yes synopsis due 2 days after review"],
    [2490, "Priya", "who's writing it"],
    [2485, "Rohan", "Sneha can you draft the synopsis?"],
    [2480, "Sneha", "sure, I'll share a draft by tomorrow evening"],
    [2475, "Rohan", "ACTION for Sneha: synopsis draft by tomorrow evening"],
    [2400, "Priya", "reminder: everyone submit individual contribution sheet"],
    [2395, "Ananya", "where's the link"],
    [2390, "Priya", "I'll share tonight"],
    [2300, "Kabir", "does anyone have the prof's email"],
    [2295, "Rohan", "x.y@college.edu"],
    [2290, "Sneha", "please don't spam him lol"],
    [2200, "Aarav", "model file ready, 220 MB"],
    [2195, "Rohan", "can it run on a normal laptop"],
    [2190, "Aarav", "yes CPU inference is around 200ms"],
    [2185, "Priya", "perfect for demo"],
    [2100, "Ananya", "design system done, using blue #1b62f5"],
    [2095, "Priya", "nice"],
    [2000, "Rohan", "IMPORTANT: Review presentation is on " + d(3) + " at 10am, hall 2"],
    [1995, "Priya", "noted 📌"],
    [1990, "Sneha", "noted"],
    [1985, "Kabir", "noted"],
    [1980, "Ananya", "noted"],
    [1900, "Priya", "we need a deck, who makes it"],
    [1895, "Ananya", "I can do the visual part if someone gives content"],
    [1890, "Rohan", "Aarav can you prepare the ML slides?"],
    [1885, "Aarav", "sure"],
    [1880, "Rohan", "ACTION for Aarav: ML + model accuracy slides"],
    [1800, "Kabir", "what about the live demo part"],
    [1795, "Rohan", "we'll demo face scan live"],
    [1790, "Kabir", "risky, what if wifi fails"],
    [1785, "Rohan", "run everything locally then"],
    [1780, "Priya", "yes local demo, no internet"],
    [1700, "Sneha", "synopsis draft done, sharing now"],
    [1695, "Sneha", "<Media omitted>"],
    [1690, "Priya", "reading now"],
    [1685, "Rohan", "looks good, minor fixes"],
    [1600, "Ananya", "deck template ready, adding slides"],
    [1595, "Kabir", "can I add the budget slide"],
    [1590, "Rohan", "sure"],
    [1550, "Priya", "guys the prof changed the submission date"],
    [1548, "Rohan", "to when"],
    [1545, "Priya", "report submission moved from " + d(2) + " to " + d(4)],
    [1540, "Sneha", "phew, more time"],
    [1538, "Kabir", "yes!"],
    [1535, "Priya", "DECISION UPDATE: Report submission deadline extended to " + d(4)],
    [1500, "Rohan", "reminder to back up your work"],
    [1495, "Aarav", "pushed to git"],
    [1490, "Ananya", "same"],
    [1400, "Sneha", "can someone review my synopsis section 3"],
    [1395, "Kabir", "I'll look"],
    [1390, "Sneha", "thanks"],
    [1300, "Priya", "venue for the meeting changed, library is booked"],
    [1295, "Rohan", "where to"],
    [1290, "Priya", "seminar hall, same Wednesday 3pm"],
    [1285, "Rohan", "DECISION UPDATE: Meeting venue changed from library to seminar hall, Wednesday 3pm"],
    [1280, "Ananya", "noted"],
    [1200, "Aarav", "added confusion matrix to slides"],
    [1195, "Rohan", "good"],
    [1190, "Kabir", "the deck looks 🔥"],
    [1100, "Priya", "does anyone remember the wifi password in seminar hall"],
    [1095, "Ananya", "no idea"],
    [1090, "Rohan", "ask the lab assistant"],
    [1000, "Sneha", "I'll bring an extension cord"],
    [995, "Priya", "lifesaver"],
    [900, "Rohan", "everyone please check the deck once before the meeting"],
    [895, "Priya", "will do"],
    [890, "Ananya", "done"],
    [885, "Kabir", "done"],
    [884, "Sneha", "won't be able to, travelling"],
    [880, "Rohan", "no worries, review later"],
    [800, "Aarav", "deck reviewed, fixed a typo on slide 7"],
    [795, "Rohan", "thanks"],
    [700, "Priya", "guys I got the OTP for the college portal: 482913"],
    [695, "Ananya", "why are you sending that here 😭"],
    [690, "Priya", "oops wrong chat, ignore"],
    [685, "Kabir", "delete delete"],
    [600, "Rohan", "IMPORTANT: Bring printed report copies to the review"],
    [595, "Sneha", "how many copies"],
    [590, "Rohan", "one each for the 3 panel members"],
    [585, "Ananya", "noted"],
    [500, "Kabir", "who's printing, I can get it done nearby"],
    [495, "Rohan", "yes please, bill it to me"],
    [490, "Kabir", "ok, will print tomorrow morning"],
    [485, "Rohan", "ACTION for Kabir: print 3 report copies tomorrow morning"],
    [480, "Aarav", "thanks Kabir"],
    [420, "Priya", "final rehearsal tomorrow at 5pm, everyone join"],
    [415, "Sneha", "I'll join online"],
    [410, "Ananya", "joining"],
    [405, "Kabir", "joining"],
    [400, "Rohan", "let's run the full demo once"],
    [360, "Aarav", "we should also record a backup demo video"],
    [355, "Rohan", "good idea, @Aarav can you record it?"],
    [350, "Aarav", "sure, after the rehearsal"],
    [345, "Rohan", "ACTION for Aarav: record backup demo video after rehearsal"],
    [335, "Rohan", "@Aarav what's the inference time on your laptop? need it for the slides"],
    [330, "Aarav", "around 200ms on CPU"],
    [328, "Rohan", "ok adding that to the MLC slides"],
    [340, "Priya", "smart, wifi always fails in that hall"],
    [300, "Ananya", "I updated the deck with the new deadline"],
    [295, "Rohan", "thanks"],
    [240, "Sneha", "can't join rehearsal, but I reviewed the deck"],
    [235, "Rohan", "that's fine"],
    [200, "Kabir", "report copies printed ✅"],
    [195, "Rohan", "legend 🙌"],
    [180, "Priya", "rehearsal in 2 hours, don't forget"],
    [175, "Ananya", "coming"],
    [170, "Aarav", "coming"],
    [150, "Rohan", "IMPORTANT: Rehearsal today 5pm, seminar hall. Be on time."],
    [120, "Priya", "@Aarav did you record the backup video?"],
    [118, "Aarav", "not yet, doing it after rehearsal"],
    [115, "Priya", "ok make sure it's done before tonight"],
    [110, "Aarav", "will do"],
    [90, "Rohan", "also who is bringing the laptop with the model"],
    [85, "Aarav", "me, I have the trained model locally"],
    [80, "Rohan", "make sure it works offline"],
    [75, "Aarav", "tested offline, works"],
    [70, "Priya", "@Aarav double-check the model once more after the latest updates please"],
    [60, "Kabir", "is the seminar hall projector working?"],
    [55, "Ananya", "I checked, it works but HDMI cable is loose"],
    [50, "Priya", "I'll bring my own cable"],
    [45, "Rohan", "thanks"],
    [40, "Priya", "@Aarav are you joining the rehearsal call now?"],
    [38, "Aarav", "yes joining in 2 mins"],
    [35, "Priya", "please confirm the accuracy number for the demo script"],
    [30, "Aarav", "94.2%"],
    [25, "Rohan", "perfect, putting it on the slide"],
    [20, "Priya", "everyone share their contribution sheet link before tonight please"],
    [18, "Sneha", "shared ✅"],
    [15, "Kabir", "shared"],
    [12, "Ananya", "shared"],
    [10, "Priya", "@Aarav waiting on yours"],
    [8, "Aarav", "sharing now"],
    [5, "Rohan", "ok team, final review tomorrow, let's rest"],
    [3, "Priya", "good luck everyone 💙"],
    [1, "Kabir", "gn all"],
  ];

  return raw.map(([minutesAgo, sender, text], index) => {
    const messages: Message = {
      id: `demo-${index}`,
      sender,
      timestamp: now - minutesAgo * MINUTE,
      text,
      source: "demo",
      isSystem: sender === "System" || text.includes("<Media omitted>"),
      mentions: [],
    };
    return messages;
  }).map((message) => {
    const found = new Set<string>();
    const re = /@([\w.+-]{1,40})/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(message.text)) !== null) found.add(m[1].toLowerCase());
    return { ...message, mentions: [...found] };
  });
}
